tasks:
  hello-job:
    runner: razorci/openjdk:11-buster
    steps:
    - git --version
    - checkout
    - cache/pull:
        key: maven-repo-{{ checksum "pom.xml" }}
        fallback_key: maven-repo-
        
    - run: mvn clean test
    - reports/junit: 
      - target/surefire-reports/TEST-*.xml
